#!/usr/bin/env python3
"""Regression tests for ``zip_content_fingerprint``'s exclusion of build metadata.

The fingerprint exists to answer one question: *is this the same code that ran last time?*
It is checked against ``pipeline/toolchain-lock.json`` before anything is generated, so if it
reports a difference that is not a difference in code, the pipeline refuses to run for no
reason - and the obvious way out, re-recording the locked value, quietly turns the check into
a formality.

That is not hypothetical. ``shacl-play-app`` is a onejar, so it unpacks its dependencies, and
one of them - ``xls2rdf-lib`` - is resolved from JitPack, which **builds on demand**. Maven
stamps a generation timestamp into ``META-INF/maven/{groupId}/{artifactId}/pom.properties``,
so the same pinned commit produces a different artifact every time JitPack rebuilds it.
Measured on two cached builds of the pinned commit ``ac18090cfd``: 163 entries each, none
missing on either side, exactly one differing - ``pom.properties``, and within it only
``#Thu Aug 06 04:58:39 UTC 2026`` against ``#Fri Jul 03 16:22:50 UTC 2026``. Same
``version=4.0.2``; every class byte-identical.

So the excluded entry must be excluded. What these tests pin is that the exclusion stays
**narrow**: a changed class, a changed ``MANIFEST.MF`` or a changed ``pom.xml`` must still move
the fingerprint, and a ``pom.properties`` somewhere other than Maven's generated location must
not be skipped just because of its name.

No JDK, no Maven, no network: the jars are built inline.

Run:  python scripts/test_zip_content_fingerprint.py
"""

from __future__ import annotations

import sys
import tempfile
import zipfile
from pathlib import Path

from generate_semantic_artifacts import zip_content_fingerprint

STAMP_A = "#Thu Aug 06 04:58:39 UTC 2026"
STAMP_B = "#Fri Jul 03 16:22:50 UTC 2026"

FAILURES: list[str] = []


def check(condition: bool, what: str) -> None:
    if condition:
        print(f"  ok   {what}")
    else:
        print(f"  FAIL {what}")
        FAILURES.append(what)


def jar(directory: Path, name: str, entries: dict[str, str]) -> Path:
    path = directory / name
    with zipfile.ZipFile(path, "w") as archive:
        for entry_name, content in entries.items():
            archive.writestr(entry_name, content)
    return path


def base_entries() -> dict[str, str]:
    return {
        "fr/sparna/rdf/Foo.class": "class-bytes",
        "META-INF/MANIFEST.MF": "Manifest-Version: 1.0\nMain-Class: fr.sparna.rdf.Main\n",
        "META-INF/maven/fr.sparna.rdf.xls2rdf/xls2rdf-lib/pom.xml": "<project/>",
        "META-INF/maven/fr.sparna.rdf.xls2rdf/xls2rdf-lib/pom.properties":
            f"#Generated by Maven\n{STAMP_A}\nversion=4.0.2\n",
    }


def main() -> int:
    with tempfile.TemporaryDirectory() as tmp:
        directory = Path(tmp)
        reference = zip_content_fingerprint(jar(directory, "reference.jar", base_entries()))

        print("the JitPack rebuild case - the reason this exclusion exists")
        rebuilt = base_entries()
        rebuilt["META-INF/maven/fr.sparna.rdf.xls2rdf/xls2rdf-lib/pom.properties"] = (
            f"#Generated by Maven\n{STAMP_B}\nversion=4.0.2\n"
        )
        check(
            zip_content_fingerprint(jar(directory, "rebuilt.jar", rebuilt)) == reference,
            "a differing pom.properties build timestamp does not change the fingerprint",
        )

        print("what must still be caught")
        changed_code = base_entries()
        changed_code["fr/sparna/rdf/Foo.class"] = "DIFFERENT-class-bytes"
        check(
            zip_content_fingerprint(jar(directory, "code.jar", changed_code)) != reference,
            "a changed class changes the fingerprint",
        )

        changed_manifest = base_entries()
        changed_manifest["META-INF/MANIFEST.MF"] = (
            "Manifest-Version: 1.0\nMain-Class: fr.sparna.rdf.Other\n"
        )
        check(
            zip_content_fingerprint(jar(directory, "manifest.jar", changed_manifest)) != reference,
            "a changed MANIFEST.MF changes the fingerprint",
        )

        changed_pom = base_entries()
        changed_pom["META-INF/maven/fr.sparna.rdf.xls2rdf/xls2rdf-lib/pom.xml"] = (
            "<project><modelVersion>4.0.0</modelVersion></project>"
        )
        check(
            zip_content_fingerprint(jar(directory, "pom.jar", changed_pom)) != reference,
            "a changed pom.xml changes the fingerprint",
        )

        changed_version = base_entries()
        changed_version["META-INF/maven/fr.sparna.rdf.xls2rdf/xls2rdf-lib/pom.properties"] = (
            f"#Generated by Maven\n{STAMP_A}\nversion=4.0.3\n"
        )
        check(
            zip_content_fingerprint(jar(directory, "version.jar", changed_version)) == reference,
            "a dependency version change is NOT caught here - the lock's commit pins cover it",
        )

        print("the exclusion is matched by location, not by filename")
        elsewhere = base_entries()
        elsewhere["config/pom.properties"] = "some=value\n"
        first = zip_content_fingerprint(jar(directory, "elsewhere-a.jar", elsewhere))
        elsewhere["config/pom.properties"] = "some=other\n"
        check(
            zip_content_fingerprint(jar(directory, "elsewhere-b.jar", elsewhere)) != first,
            "a pom.properties outside META-INF/maven is still fingerprinted",
        )

        nested = base_entries()
        nested["META-INF/maven/a/b/c/pom.properties"] = "x=1\n"
        deeper = zip_content_fingerprint(jar(directory, "nested-a.jar", nested))
        nested["META-INF/maven/a/b/c/pom.properties"] = "x=2\n"
        check(
            zip_content_fingerprint(jar(directory, "nested-b.jar", nested)) != deeper,
            "the pattern does not over-match deeper paths under META-INF/maven",
        )

    print()
    if FAILURES:
        print(f"{len(FAILURES)} check(s) failed")
        return 1
    print("all checks passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
